-- AlterTable (generated by Prisma from schema.prisma)
ALTER TABLE "Device" ADD COLUMN     "installId" TEXT;

-- Hand-written tail (Prisma cannot express partial indexes or checks).
--
-- Invariant: one user + one app installation = one ACTIVE Device. The database enforces it, so two concurrent
-- sign-ins on the same installation converge on one row instead of racing a check-then-insert. The index covers
-- only active rows with an installation id: revoked rows stay as history, and legacy rows (NULL) are unaffected.
CREATE UNIQUE INDEX "Device_one_active_per_installation"
  ON "Device" ("userId", "installId")
  WHERE "installId" IS NOT NULL AND "revokedAt" IS NULL;

-- The id is a client-generated random UUID. Reject anything else at the database as well as in the route.
ALTER TABLE "Device" ADD CONSTRAINT "Device_installId_uuid"
  CHECK ("installId" IS NULL OR "installId" ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$');
