-- AlterTable (generated by Prisma from schema.prisma). Additive and nullable: existing rows and old clients are unaffected.
ALTER TABLE "Interview" ADD COLUMN     "sourceUpdatedAt" TIMESTAMP(3),
ADD COLUMN     "timeZone" TEXT;
