export interface TemplateQuestion {
  text: string;
  hint?: string;
  tags: string[];
  difficulty: number;
  type: string;
}

export interface QuestionBankTemplate {
  id: string;
  title: string;
  description: string;
  questions: TemplateQuestion[];
}

export const QUESTION_BANK_TEMPLATES: QuestionBankTemplate[] = [
  {
    id: "behavioral-50",
    title: "Top 50 Behavioral Interview Questions",
    description: "Common behavioral questions covering leadership, teamwork, conflict resolution, and problem-solving.",
    questions: [
      { text: "Tell me about a time you led a team through a difficult project.", hint: "Use STAR: Describe the situation, your specific role as leader, actions you took to guide the team, and measurable results. Include team size and project impact.", tags: ["leadership", "teamwork"], difficulty: 3, type: "BEHAVIORAL" },
      { text: "Describe a situation where you had to deal with a difficult coworker.", hint: "Focus on: the specific conflict, how you approached the conversation, what resolution was reached, and what you learned about working with different personalities.", tags: ["conflict", "communication"], difficulty: 3, type: "BEHAVIORAL" },
      { text: "Give me an example of a time you failed and what you learned.", hint: "Be honest about the failure. Describe what went wrong, why, what you learned, and how you applied that lesson to future situations. Show growth mindset.", tags: ["resilience", "growth"], difficulty: 3, type: "BEHAVIORAL" },
      { text: "Tell me about a time you had to make a decision with incomplete information.", hint: "Describe the situation, what information was missing, how you assessed risks, the decision framework you used, and the outcome.", tags: ["decision-making"], difficulty: 4, type: "BEHAVIORAL" },
      { text: "Describe a project where you had to prioritize competing demands.", hint: "Explain the competing priorities, your prioritization framework (urgency vs importance), how you communicated tradeoffs to stakeholders, and the results.", tags: ["prioritization", "time-management"], difficulty: 3, type: "BEHAVIORAL" },
      { text: "Tell me about a time you went above and beyond for a customer or user.", hint: "Describe who the customer was, what their need was, what extra effort you put in beyond your role, and the impact it had.", tags: ["customer-focus"], difficulty: 2, type: "BEHAVIORAL" },
      { text: "Give an example of when you had to adapt to a significant change at work.", hint: "Describe the change, your initial reaction, how you adapted your approach, and what the outcome was. Show flexibility.", tags: ["adaptability"], difficulty: 3, type: "BEHAVIORAL" },
      { text: "Tell me about a time you mentored or coached someone.", hint: "Describe who you mentored, what they needed help with, your approach to teaching/coaching, and the improvement they showed.", tags: ["leadership", "mentoring"], difficulty: 3, type: "BEHAVIORAL" },
      { text: "Describe a situation where you had to influence others without authority.", hint: "Explain who you needed to influence, why you lacked formal authority, what persuasion techniques you used, and the result.", tags: ["influence", "leadership"], difficulty: 4, type: "BEHAVIORAL" },
      { text: "Tell me about a time you identified and solved a problem before it became critical.", hint: "Describe how you noticed the problem early, what analysis you did, the proactive steps you took, and the impact of early intervention.", tags: ["problem-solving", "proactive"], difficulty: 3, type: "BEHAVIORAL" },
    ],
  },
  {
    id: "system-design",
    title: "Technical System Design Questions",
    description: "System design and architecture questions for engineering interviews.",
    questions: [
      { text: "How would you design a URL shortener like bit.ly?", hint: "Key components: hashing/encoding algorithm, database schema (short_code, original_url, created_at), redirect service, analytics tracking. Consider: collision handling, custom URLs, expiration, rate limiting, caching with Redis, and horizontal scaling.", tags: ["system-design", "web"], difficulty: 3, type: "TECHNICAL" },
      { text: "Design a real-time chat application.", hint: "Key decisions: WebSocket vs SSE vs long polling, message storage (SQL vs NoSQL), presence tracking, message delivery guarantees (at-least-once), group chats, read receipts. Consider: connection management, horizontal scaling with pub/sub, offline message queue.", tags: ["system-design", "real-time"], difficulty: 4, type: "TECHNICAL" },
      { text: "How would you design a rate limiter?", hint: "Algorithms: token bucket, sliding window, fixed window. Storage: Redis for distributed rate limiting. Consider: per-user vs per-IP vs per-API-key, different limits for different endpoints, burst handling, distributed consistency.", tags: ["system-design", "infrastructure"], difficulty: 3, type: "TECHNICAL" },
      { text: "Design a notification system that supports email, SMS, and push notifications.", hint: "Architecture: notification service, template engine, delivery channels (email/SMS/push adapters), preference management, retry logic. Consider: priority levels, batching, rate limiting per channel, delivery tracking, unsubscribe handling.", tags: ["system-design", "distributed"], difficulty: 4, type: "TECHNICAL" },
      { text: "How would you design a file storage service like Dropbox?", hint: "Key components: file chunking, deduplication, metadata service, sync protocol, conflict resolution. Consider: chunk-level sync (delta sync), compression, CDN for distribution, versioning, sharing permissions, encryption at rest.", tags: ["system-design", "storage"], difficulty: 5, type: "TECHNICAL" },
      { text: "What is the CAP theorem and how does it apply to distributed databases?", hint: "CAP: Consistency, Availability, Partition tolerance - can only guarantee 2 of 3. CP systems (e.g., HBase, MongoDB): strong consistency, may be unavailable during partitions. AP systems (e.g., Cassandra, DynamoDB): always available, eventually consistent. Real-world: partitions are inevitable, so the real choice is between C and A.", tags: ["databases", "distributed-systems"], difficulty: 3, type: "DEFINITION" },
      { text: "Explain the difference between horizontal and vertical scaling.", hint: "Vertical scaling: adding more resources (CPU, RAM) to existing server. Horizontal scaling: adding more servers. Vertical is simpler but has limits. Horizontal requires: load balancing, data partitioning, stateless services, session management. Most production systems use horizontal scaling.", tags: ["scalability", "infrastructure"], difficulty: 2, type: "DEFINITION" },
    ],
  },
  {
    id: "investor-qa",
    title: "Investor Q&A for Startups",
    description: "Common questions investors ask during pitch meetings and due diligence.",
    questions: [
      { text: "What problem are you solving and for whom?", hint: "State the problem in one sentence. Quantify the pain point (time wasted, money lost, inefficiency). Define your target customer precisely. Use a specific example or story.", tags: ["pitch", "problem"], difficulty: 2, type: "PITCH" },
      { text: "What is your unique competitive advantage?", hint: "Explain what you do differently (not just better). Address: proprietary technology, network effects, data moat, team expertise, or unique market insight. Explain why this advantage is defensible and hard to replicate.", tags: ["pitch", "competition"], difficulty: 3, type: "PITCH" },
      { text: "What is your business model and how do you make money?", hint: "Clearly state: who pays, how much, how often (subscription, transaction, freemium). Include current revenue/ARR if applicable. Show unit economics: CAC, LTV, gross margin. Explain pricing strategy rationale.", tags: ["pitch", "business-model"], difficulty: 3, type: "PITCH" },
      { text: "What are your key metrics and how are they trending?", hint: "Share 3-5 key metrics: MRR/ARR, user growth rate, retention/churn, engagement metrics. Show month-over-month or year-over-year trends. Highlight inflection points. Be honest about metrics that need improvement.", tags: ["pitch", "metrics"], difficulty: 3, type: "PITCH" },
      { text: "How will you use this funding?", hint: "Break down by category: engineering (X%), sales/marketing (Y%), operations (Z%). Explain what milestones this funding will help you reach. Be specific about timeline (12-18 months). Show how this leads to the next funding round or profitability.", tags: ["pitch", "fundraising"], difficulty: 3, type: "PITCH" },
      { text: "What is your go-to-market strategy?", hint: "Describe your customer acquisition channels. Explain your sales motion (self-serve, inside sales, enterprise). Share current CAC and target. Describe launch strategy for new markets. Include partnerships or distribution advantages.", tags: ["pitch", "go-to-market"], difficulty: 4, type: "PITCH" },
      { text: "Who is on your team and why are you the right people to build this?", hint: "Highlight relevant domain expertise, previous exits or successes, technical capabilities, and complementary skills. Address any gaps in the team and your plan to fill them.", tags: ["pitch", "team"], difficulty: 2, type: "PITCH" },
      { text: "What keeps you up at night about this business?", hint: "Be honest and self-aware. Mention 1-2 real risks (market risk, execution risk, regulatory). For each risk, explain your mitigation strategy. Shows investor maturity and strategic thinking.", tags: ["pitch", "risk"], difficulty: 4, type: "PITCH" },
    ],
  },
  {
    id: "design-engineer-technical",
    title: "Design Engineer Technical Questions",
    description: "Technical questions covering React, CSS, component architecture, design systems, accessibility, and frontend performance. Tailored for Design Engineer and Frontend Engineer roles.",
    questions: [
      { text: "Explain the difference between CSS Grid and Flexbox. When would you use each?", hint: "Grid is for two-dimensional layouts (rows AND columns simultaneously). Flexbox is for one-dimensional layouts (a single row OR column). Use Grid for page layouts, dashboard grids, and complex component arrangements. Use Flexbox for navigation bars, card rows, centering content, and distributing space in one direction.", tags: ["css", "layout"], difficulty: 2, type: "DEFINITION" },
      { text: "What are design tokens and why do they matter?", hint: "Design tokens are the smallest units of a design system: colours, spacing, typography, shadows, border radii stored as platform-agnostic variables. They create a single source of truth, enable theming, and make large-scale changes trivial. Structured as primitive tokens (blue-500) mapped to semantic tokens (color-primary) mapped to component tokens (button-bg).", tags: ["design-systems", "architecture"], difficulty: 3, type: "DEFINITION" },
      { text: "How would you implement a compound component pattern in React?", hint: "Compound components share implicit state via React Context. Parent provides context, children consume it. Example: Tabs.Root manages active tab state, Tabs.Trigger updates it, Tabs.Content renders the active panel. Benefits: flexible composition, clean API, separation of concerns.", tags: ["react", "patterns", "components"], difficulty: 3, type: "TECHNICAL" },
      { text: "How do you ensure accessibility in a component library?", hint: "Start with semantic HTML. Add ARIA attributes when HTML semantics are insufficient. Implement keyboard navigation. Manage focus: trap in modals, return on close. Use aria-live regions for dynamic content. Ensure 4.5:1 colour contrast (WCAG AA). Test with screen readers. Follow WAI-ARIA Authoring Practices.", tags: ["accessibility", "design-systems"], difficulty: 3, type: "TECHNICAL" },
      { text: "Explain React Server Components vs Client Components.", hint: "Server Components render on the server, never ship JS to client, can access databases directly. Client Components use useState, useEffect, event handlers. Use Server Components by default. Add 'use client' only when you need interactivity. Server Components can import Client Components but not vice versa.", tags: ["react", "nextjs", "architecture"], difficulty: 3, type: "DEFINITION" },
      { text: "What are the key considerations when building a component library from scratch?", hint: "Token architecture, API design (composition over configuration), accessibility (WCAG AA), styling strategy with theming, documentation (Storybook), testing (unit, visual regression, a11y), versioning (semver, changelogs), and tree-shaking.", tags: ["design-systems", "architecture"], difficulty: 4, type: "TECHNICAL" },
      { text: "How does the browser rendering pipeline work?", hint: "Parse HTML > DOM tree. Parse CSS > CSSOM. Combine > Render tree. Layout > calculate positions. Paint > fill pixels. Composite > combine layers. Reflow is expensive (dimension changes). Repaint is cheaper (colour changes). Compositing is cheapest (transform, opacity).", tags: ["performance", "browser"], difficulty: 3, type: "DEFINITION" },
      { text: "How would you implement dark mode in a design system?", hint: "CSS custom properties mapping semantic tokens to light/dark values. Toggle via data-theme attribute or prefers-color-scheme. Store preference in localStorage, fall back to system preference. Consider: images may need different versions, shadows need adjustment, contrast issues.", tags: ["design-systems", "css", "theming"], difficulty: 3, type: "TECHNICAL" },
      { text: "Explain the stacking context in CSS and how z-index works.", hint: "A stacking context is created by positioned elements with z-index, opacity < 1, transform/filter properties. z-index only works on positioned elements and flex/grid children. Values are scoped to their stacking context: z-index 999 inside a lower context still appears behind z-index 1 in a higher context.", tags: ["css", "layout"], difficulty: 3, type: "DEFINITION" },
      { text: "Explain CSS animations vs JavaScript animations. When would you use each?", hint: "CSS animations: hardware-accelerated for transform/opacity, declarative, simpler. Use for hover effects, spinners, transitions. JS animations: imperative control, dynamic values, chaining. Use for complex sequences, physics-based motion, scroll-driven. Libraries: Framer Motion, GSAP. Web Animations API bridges both.", tags: ["css", "animation", "performance"], difficulty: 3, type: "DEFINITION" },
    ],
  },
  {
    id: "design-engineer-behavioral",
    title: "Design Engineer Behavioral Questions",
    description: "Behavioral questions specific to Design Engineer roles: design systems, cross-functional collaboration, accessibility advocacy, and creative-technical thinking.",
    questions: [
      { text: "Tell me about a time you built a design system or component library from scratch. What decisions did you make and why?", hint: "Structure: problem (inconsistent UI), token architecture, first components built, API design decisions, accessibility approach, measurable impact (dev speed, consistency, adoption).", tags: ["design-systems", "leadership", "architecture"], difficulty: 4, type: "BEHAVIORAL" },
      { text: "Describe a time you had to push back on a design that was technically difficult or impossible to implement well.", hint: "What was the design? Why problematic (performance, a11y, maintenance)? How did you communicate without being dismissive? What alternative did you propose? Show respect for design while advocating for users.", tags: ["collaboration", "communication", "design"], difficulty: 3, type: "BEHAVIORAL" },
      { text: "How do you approach accessibility in your work? Give a specific example.", hint: "Show it is part of your process, not an afterthought. Example: audited component, found issues, fixed them. Mention tools (axe, Lighthouse, screen readers). Cover ARIA patterns. End with impact.", tags: ["accessibility", "process"], difficulty: 3, type: "BEHAVIORAL" },
      { text: "Tell me about a time you improved performance on a frontend application.", hint: "Identify problem (Core Web Vitals, user complaints). Investigation (DevTools, profiling). Root cause (large bundle, layout thrashing, unnecessary re-renders). Solution (code splitting, lazy loading, memoisation). Quantify result.", tags: ["performance", "problem-solving"], difficulty: 3, type: "BEHAVIORAL" },
      { text: "Describe a project where you worked closely with designers. How did you collaborate?", hint: "Workflow: Figma reviews, design critiques, shared component inventory. How you gave feedback and handled changes. Show you speak both design vocabulary and engineering vocabulary.", tags: ["collaboration", "design", "communication"], difficulty: 3, type: "BEHAVIORAL" },
      { text: "Tell me about a complex animation or interaction you built. Walk me through your approach.", hint: "What interaction? What tools (CSS, Framer Motion, GSAP, Three.js)? Performance handling (rAF, GPU properties)? Accessibility (prefers-reduced-motion, keyboard alternatives)? Show creative-technical thinking.", tags: ["animation", "creative-tech", "technical"], difficulty: 4, type: "BEHAVIORAL" },
      { text: "How do you stay current with frontend and design engineering trends?", hint: "Be specific about sources. Show depth: evaluate trends critically. Give an example of something learned recently and applied. Mention side projects.", tags: ["growth", "learning"], difficulty: 2, type: "BEHAVIORAL" },
      { text: "Describe your experience with design-to-code workflows. How do you translate designs into code?", hint: "Process with Figma: extracting tokens, handling responsive behaviour not specified in designs. Communicating back when something does not work. Auto-layout mapping to code. Think in systems, not screens.", tags: ["design", "workflow", "collaboration"], difficulty: 3, type: "BEHAVIORAL" },
      { text: "Tell me about a feature you shipped that you are particularly proud of.", hint: "What was the feature and why did it matter? What was technically interesting? What challenges? How did you measure success? What would you do differently? Show both technical depth and product thinking.", tags: ["impact", "product-thinking", "technical"], difficulty: 3, type: "BEHAVIORAL" },
      { text: "Tell me about a time you had to balance user experience with technical constraints.", hint: "What was the constraint (browser support, performance budget, API limitations)? What was the ideal UX? How did you find a middle ground? How did you communicate to stakeholders? Show you advocate for users within realistic boundaries.", tags: ["trade-offs", "communication", "ux"], difficulty: 3, type: "BEHAVIORAL" },
    ],
  },
  {
    id: "frontend-system-design",
    title: "Frontend System Design Questions",
    description: "System design questions focused on frontend architecture, component systems, and web application design. Common in senior Design Engineer and Frontend Engineer interviews.",
    questions: [
      { text: "Design a component library architecture. How would you structure it?", hint: "Cover: monorepo vs multi-package, token system, component categories, styling approach, documentation (Storybook), testing strategy, publishing, and developer experience.", tags: ["design-systems", "architecture"], difficulty: 4, type: "TECHNICAL" },
      { text: "Design an infinite scroll feed like Twitter/X.", hint: "Virtualised list, Intersection Observer, cursor-based pagination, optimistic updates, skeleton loading, scroll restoration, error boundaries, accessibility, and CSS contain for performance.", tags: ["frontend", "performance", "architecture"], difficulty: 4, type: "TECHNICAL" },
      { text: "Design a drag-and-drop kanban board like Trello.", hint: "Pointer events over HTML5 DnD, optimistic reordering, normalised state, drop zone detection, CSS transform animations, keyboard accessibility, debounced API persistence.", tags: ["frontend", "interaction", "architecture"], difficulty: 4, type: "TECHNICAL" },
      { text: "Design a search experience with autocomplete, filters, and results.", hint: "Debounced input, ARIA combobox pattern, keyboard navigation, faceted filters with URL state, result highlighting, AbortController for cancelling stale requests, empty and error states.", tags: ["frontend", "ux", "architecture"], difficulty: 3, type: "TECHNICAL" },
      { text: "Design a theming system that supports light mode, dark mode, and custom brand themes.", hint: "CSS custom properties, semantic token mapping, runtime switching via data attribute, system preference detection, localStorage persistence, smooth transitions, image handling across themes.", tags: ["design-systems", "css", "architecture"], difficulty: 3, type: "TECHNICAL" },
      { text: "Design a state management solution for a large React application.", hint: "Compare: Context + useReducer, Zustand, Jotai, Redux Toolkit. Server state: TanStack Query. URL state: nuqs. Principle: collocate state close to where it is used. Global state only when truly needed.", tags: ["react", "state-management", "architecture"], difficulty: 4, type: "TECHNICAL" },
      { text: "Design a performance optimisation strategy for a Next.js application.", hint: "SSG > SSR > CSR. next/image, next/font, bundle analysis, code splitting, React Server Components, caching headers, Core Web Vitals monitoring, third-party script loading strategy.", tags: ["nextjs", "performance", "architecture"], difficulty: 4, type: "TECHNICAL" },
      { text: "Design a multi-step form wizard with validation.", hint: "State machine for step progression, per-step Zod validation, localStorage persistence, conditional steps, progress indicator, focus management on step change, error announcements, retry on submission failure.", tags: ["frontend", "forms", "architecture"], difficulty: 3, type: "TECHNICAL" },
    ],
  },
  {
    id: "javascript-deep-dive",
    title: "JavaScript & TypeScript Deep Dive",
    description: "Core JavaScript concepts frequently tested in frontend interviews: closures, event loop, prototypes, async patterns, and modern JS features.",
    questions: [
      { text: "Explain closures in JavaScript. Give a practical example.", hint: "A closure is a function that retains access to variables from its enclosing scope after the outer function returns. Used in: module pattern, event handlers, React hooks (useState), debounce/throttle, private variables.", tags: ["javascript", "fundamentals"], difficulty: 2, type: "DEFINITION" },
      { text: "What is the event loop? Explain microtasks vs macrotasks.", hint: "Event loop: call stack > microtasks > one macrotask > repeat. Microtasks: Promise callbacks, queueMicrotask. Macrotasks: setTimeout, I/O, UI rendering. Microtasks always run before the next macrotask.", tags: ["javascript", "async", "fundamentals"], difficulty: 3, type: "DEFINITION" },
      { text: "Explain prototypal inheritance in JavaScript.", hint: "Every object has a [[Prototype]] link. Property access walks the chain. Object.create(proto) creates with specific prototype. ES6 classes are syntactic sugar. Chain: instance > Constructor.prototype > Object.prototype > null.", tags: ["javascript", "fundamentals"], difficulty: 3, type: "DEFINITION" },
      { text: "What is the this keyword? How does it work in different contexts?", hint: "Depends on call site: global (window), method (the object), constructor (new instance), arrow function (lexical/enclosing this), call/apply/bind (explicit). Common mistake: losing this in callbacks.", tags: ["javascript", "fundamentals"], difficulty: 3, type: "DEFINITION" },
      { text: "Explain async/await, Promises, and how they relate.", hint: "Promises: pending/fulfilled/rejected. async/await is syntactic sugar. async functions return Promises. await pauses until settled. Error handling: try/catch. Patterns: Promise.all (parallel), Promise.allSettled, Promise.race.", tags: ["javascript", "async"], difficulty: 3, type: "DEFINITION" },
      { text: "What is the Proxy object? Give a practical use case.", hint: "Proxy intercepts operations (get, set, has, etc.) via handler traps. Use cases: reactive state (Vue 3), validation, logging, observable patterns, default values.", tags: ["javascript", "advanced"], difficulty: 4, type: "DEFINITION" },
      { text: "Explain event delegation and why it matters.", hint: "Leverages event bubbling: one handler on parent instead of many on children. Check event.target to identify source. Benefits: fewer listeners, works for dynamic elements, simpler code.", tags: ["javascript", "dom", "performance"], difficulty: 2, type: "DEFINITION" },
      { text: "What are Web Workers and when would you use them?", hint: "Background threads for heavy computation without blocking UI. Cannot access DOM. Communicate via postMessage. SharedWorker for cross-tab. Service Workers for network interception. Use for: image processing, parsing, encryption.", tags: ["javascript", "performance", "browser"], difficulty: 3, type: "DEFINITION" },
      { text: "Explain the module system: CommonJS vs ES Modules.", hint: "CJS: require/module.exports, synchronous, dynamic. ESM: import/export, async, static (enables tree shaking). ESM exports are live bindings. ESM has top-level await. Use ESM for new projects.", tags: ["javascript", "modules"], difficulty: 3, type: "DEFINITION" },
      { text: "Explain structured clone vs JSON serialisation for deep copying.", hint: "JSON: loses undefined, functions, Dates, RegExp, Maps, Sets, circular refs. structuredClone: handles all those except functions and DOM nodes. structuredClone is the correct modern choice.", tags: ["javascript", "fundamentals"], difficulty: 2, type: "DEFINITION" },
    ],
  },
];
